[package]
name = "radix-yew-dismissable-layer"
description = "Yew port of Radix Dismissable Layer."

authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
web-sys = { workspace = true, features = ["CustomEvent"] }
yew.workspace = true
