[package]
name = "radix-yew-collection"
description = "Yew port of Radix Collection."

authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
nanoid = "0.4.0"
web-sys.workspace = true
yew.workspace = true
