- name: 'type: bug'
  description: 'Bug'
  color: '0090ff'
- name: 'type: documentation'
  description: 'Documentation'
  color: '0090ff'
- name: 'type: feature'
  description: 'Feature'
  color: '0090ff'
- name: 'type: maintenance'
  description: 'Maintenance'
  color: '0090ff'
- name: 'type: question'
  description: 'Question'
  color: '0090ff'

- name: 'part: colors'
  description: 'Radix Colors'
  color: 'e54d2e'
- name: 'part: icons'
  description: 'Radix Icons'
  color: 'e54d2e'
- name: 'part: primitives'
  description: 'Radix Primitives'
  color: 'e54d2e'
- name: 'part: themes'
  description: 'Radix Themes'
  color: 'e54d2e'

- name: 'framework: dioxus'
  description: 'Dioxus'
  color: 'ab4aba'
- name: 'framework: leptos'
  description: 'Leptos'
  color: 'ab4aba'
- name: 'framework: yew'
  color: 'ab4aba'
  description: 'Yew'

- name: 'component: accessible icon'
  description: 'Accessible Icon'
  color: 'ffc53d'
- name: 'component: accordion'
  description: 'Accordion'
  color: 'ffc53d'
- name: 'component: alert dialog'
  description: 'Alert Dialog'
  color: 'ffc53d'
- name: 'component: arrow'
  description: 'Arrow'
  color: 'ffc53d'
- name: 'component: aspect ratio'
  description: 'Aspect Ratio'
  color: 'ffc53d'
- name: 'component: avatar'
  description: 'Avatar'
  color: 'ffc53d'
- name: 'component: badge'
  description: 'Badge'
  color: 'ffc53d'
- name: 'component: base button'
  description: 'Base Button'
  color: 'ffc53d'
- name: 'component: blockquote'
  description: 'Blockquote'
  color: 'ffc53d'
- name: 'component: box'
  description: 'Box'
  color: 'ffc53d'
- name: 'component: button'
  description: 'Button'
  color: 'ffc53d'
- name: 'component: callout'
  description: 'Callout'
  color: 'ffc53d'
- name: 'component: card'
  description: 'Card'
  color: 'ffc53d'
- name: 'component: checkbox'
  description: 'Checkbox'
  color: 'ffc53d'
- name: 'component: checkbox cards'
  description: 'Checkbox Cards'
  color: 'ffc53d'
- name: 'component: checkbox group'
  description: 'Checkbox Group'
  color: 'ffc53d'
- name: 'component: code'
  description: 'Code'
  color: 'ffc53d'
- name: 'component: collapsible'
  description: 'Collapsible'
  color: 'ffc53d'
- name: 'component: collection'
  description: 'Collection'
  color: 'ffc53d'
- name: 'component: container'
  description: 'Container'
  color: 'ffc53d'
- name: 'component: context'
  description: 'Context'
  color: 'ffc53d'
- name: 'component: context menu'
  description: 'Context Menu'
  color: 'ffc53d'
- name: 'component: data list'
  description: 'Data List'
  color: 'ffc53d'
- name: 'component: dialog'
  description: 'Dialog'
  color: 'ffc53d'
- name: 'component: direction'
  description: 'Direction'
  color: 'ffc53d'
- name: 'component: dismissable layer'
  description: 'Dismissable Layer'
  color: 'ffc53d'
- name: 'component: dropdown menu'
  description: 'Dropdown Menu'
  color: 'ffc53d'
- name: 'component: em'
  description: 'Em'
  color: 'ffc53d'
- name: 'component: flex'
  description: 'Flex'
  color: 'ffc53d'
- name: 'component: focus guards'
  description: 'Focus Guards'
  color: 'ffc53d'
- name: 'component: focus scope'
  description: 'Focus Scope'
  color: 'ffc53d'
- name: 'component: form'
  description: 'Form'
  color: 'ffc53d'
- name: 'component: grid'
  description: 'Grid'
  color: 'ffc53d'
- name: 'component: heading'
  description: 'Heading'
  color: 'ffc53d'
- name: 'component: hover card'
  description: 'Hover Card'
  color: 'ffc53d'
- name: 'component: icon button'
  description: 'Icon Button'
  color: 'ffc53d'
- name: 'component: inset'
  description: 'Inset'
  color: 'ffc53d'
- name: 'component: kbd'
  description: 'Kbd'
  color: 'ffc53d'
- name: 'component: label'
  description: 'Label'
  color: 'ffc53d'
- name: 'component: link'
  description: 'Link'
  color: 'ffc53d'
- name: 'component: menu'
  description: 'Menu'
  color: 'ffc53d'
- name: 'component: menubar'
  description: 'Menubar'
  color: 'ffc53d'
- name: 'component: navigation menu'
  description: 'Navigation Menu'
  color: 'ffc53d'
- name: 'component: popover'
  description: 'Popover'
  color: 'ffc53d'
- name: 'component: popper'
  description: 'Popper'
  color: 'ffc53d'
- name: 'component: portal'
  description: 'Portal'
  color: 'ffc53d'
- name: 'component: presence'
  description: 'Presence'
  color: 'ffc53d'
- name: 'component: primitive'
  description: 'Primitive'
  color: 'ffc53d'
- name: 'component: progress'
  description: 'Progress'
  color: 'ffc53d'
- name: 'component: quote'
  description: 'Quote'
  color: 'ffc53d'
- name: 'component: radio'
  description: 'Radio'
  color: 'ffc53d'
- name: 'component: radio cards'
  description: 'Radio Cards'
  color: 'ffc53d'
- name: 'component: radio group'
  description: 'Radio Group'
  color: 'ffc53d'
- name: 'component: reset'
  description: 'Reset'
  color: 'ffc53d'
- name: 'component: roving focus'
  description: 'Roving Focus'
  color: 'ffc53d'
- name: 'component: scroll area'
  description: 'Scroll Area'
  color: 'ffc53d'
- name: 'component: section'
  description: 'Section'
  color: 'ffc53d'
- name: 'component: segmented control'
  description: 'Segmented Control'
  color: 'ffc53d'
- name: 'component: select'
  description: 'Select'
  color: 'ffc53d'
- name: 'component: separator'
  description: 'Separator'
  color: 'ffc53d'
- name: 'component: skeleton'
  description: 'Skeleton'
  color: 'ffc53d'
- name: 'component: slider'
  description: 'Slider'
  color: 'ffc53d'
- name: 'component: spinner'
  description: 'Spinner'
  color: 'ffc53d'
- name: 'component: strong'
  description: 'Strong'
  color: 'ffc53d'
- name: 'component: switch'
  description: 'Switch'
  color: 'ffc53d'
- name: 'component: tab nav'
  description: 'Tab Nav'
  color: 'ffc53d'
- name: 'component: table'
  description: 'Table'
  color: 'ffc53d'
- name: 'component: tabs'
  description: 'Tabs'
  color: 'ffc53d'
- name: 'component: text'
  description: 'Text'
  color: 'ffc53d'
- name: 'component: text area'
  description: 'Text Area'
  color: 'ffc53d'
- name: 'component: text field'
  description: 'Text Field'
  color: 'ffc53d'
- name: 'component: theme'
  description: 'Theme'
  color: 'ffc53d'
- name: 'component: theme panel'
  description: 'Theme Panel'
  color: 'ffc53d'
- name: 'component: toast'
  description: 'Toast'
  color: 'ffc53d'
- name: 'component: toggle'
  description: 'Toggle'
  color: 'ffc53d'
- name: 'component: toggle group'
  description: 'Toggle Group'
  color: 'ffc53d'
- name: 'component: toolbar'
  description: 'Toolbar'
  color: 'ffc53d'
- name: 'component: tooltip'
  description: 'Tooltip'
  color: 'ffc53d'
- name: 'component: visually hidden'
  description: 'Visually Hidden'
  color: 'ffc53d'
