[package]
name = "radix-yew-checkbox"
description = "Yew port of Radix Checkbox."
homepage = "https://radix.rustforweb.org/primitives/components/checkbox.html"

authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
radix-yew-presence = { path = "../presence", version = "0.0.2" }
radix-yew-primitive = { path = "../primitive", version = "0.0.2" }
radix-yew-use-controllable-state = { path = "../use-controllable-state", version = "0.0.2" }
radix-yew-use-previous = { path = "../use-previous", version = "0.0.2" }
radix-yew-use-size = { path = "../use-size", version = "0.0.2" }
web-sys = { workspace = true, features = [
    "Event",
    "EventInit",
    "HtmlButtonElement",
    "HtmlFormElement",
] }
yew.workspace = true
yew-struct-component.workspace = true
yew-style.workspace = true
