[package]
name = "radix-yew-arrow"
description = "Yew port of Radix Arrow."

authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
yew.workspace = true
