[package]
name = "radix-yew-use-previous"
description = "Yew port of Radix Use Previous."

authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
yew.workspace = true
