[package]
name = "radix-yew-label"
description = "Yew port of Radix Label."
homepage = "https://radix.rustforweb.org/primitives/components/label.html"

authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
web-sys.workspace = true
yew.workspace = true
yew-struct-component.workspace = true
yew-style.workspace = true
