[package]
name = "radix-yew-compose-refs"
description = "Yew port of Radix Compose Refs."

authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
log.workspace = true
yew.workspace = true
