[package]
name = "radix-yew-separator"
description = "Yew port of Radix Separator."
homepage = "https://radix.rustforweb.org/primitives/components/separator.html"

authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
yew.workspace = true
yew-struct-component.workspace = true
yew-style.workspace = true
