[package]
name = "radix-leptos-icons"
description = "Leptos port of Radix Icons."
homepage = "https://radix.rustforweb.org/icons/index.html"

authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
leptos.workspace = true
