[package]
name = "radix-yew-book-themes"
description = "Book examples for Radix Themes Yew."
publish = false

authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
console_error_panic_hook.workspace = true
console_log.workspace = true
log.workspace = true
radix-yew-icons = { path = "../../../packages/icons/yew" }
radix-yew-themes = { path = "../../../packages/themes/yew" }
yew = { workspace = true, features = ["csr"] }

[features]
default = [
    "box",
    "button",
    "button-color",
    "button-high-contrast",
    "button-loading",
    "button-loading-spinner",
    "button-radius",
    "button-size",
    "button-variant",
    "button-variant-ghost",
    "button-with-icons",
    "container",
    "flex",
    "grid",
    "grid-responsive",
    "heading",
    "heading-align",
    "heading-as",
    "heading-color",
    "heading-high-contrast",
    "heading-size",
    "heading-trim",
    "heading-trim-box",
    "heading-truncate",
    "heading-weight",
    "heading-wrap",
    "section",
    "select",
    "switch",
    "switch-alignment",
    "switch-color",
    "switch-disabled",
    "switch-high-contrast",
    "switch-radius",
    "switch-size",
    "switch-variant",
]
box = []
button = ["radix-yew-icons/bookmark"]
button-color = []
button-high-contrast = []
button-loading = []
button-loading-spinner = ["radix-yew-icons/bookmark"]
button-radius = []
button-size = []
button-variant = []
button-variant-ghost = []
button-with-icons = ["radix-yew-icons/bookmark"]
container = []
flex = []
grid = []
grid-responsive = []
heading = []
heading-align = []
heading-as = []
heading-color = []
heading-high-contrast = []
heading-size = []
heading-trim = []
heading-trim-box = []
heading-truncate = []
heading-weight = []
heading-wrap = []
section = []
select = []
switch = []
switch-alignment = []
switch-color = []
switch-disabled = []
switch-high-contrast = []
switch-radius = []
switch-size = []
switch-variant = []
