[package]
name = "radix-yew-book-themes"
description = "Book examples for Radix Themes Yew."
publish = false

authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
console_error_panic_hook.workspace = true
console_log.workspace = true
log.workspace = true
radix-yew-icons = { path = "../../../packages/icons/yew" }
radix-yew-themes = { path = "../../../packages/themes/yew" }
yew = { workspace = true, features = ["csr"] }
yew-router.workspace = true

[features]
default = [
    "avatar",
    "blockquote",
    "box",
    "button",
    "code",
    "container",
    "em",
    "flex",
    "grid",
    "heading",
    "kbd",
    "link",
    "quote",
    "section",
    "select",
    "strong",
    "switch",
    "text",
]
avatar = []
blockquote = []
box = []
button = ["radix-yew-icons/bookmark"]
code = []
container = []
em = []
flex = []
grid = []
heading = []
kbd = []
link = []
quote = []
section = []
select = []
strong = []
switch = []
text = []
