[package]
name = "radix-yew-book-themes"
description = "Book examples for Radix Themes Yew."
publish = false

authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
console_error_panic_hook.workspace = true
console_log.workspace = true
log.workspace = true
radix-yew-themes = { path = "../../../packages/themes/yew" }
yew = { workspace = true, features = ["csr"] }

[features]
default = [
    "box",
    "container",
    "flex",
    "grid",
    "grid-responsive",
    "section",
    "switch",
    "switch-size",
    "switch-variant",
    "switch-color",
    "switch-high-contrast",
    "switch-radius",
    "switch-alignment",
    "switch-disabled",
]
box = []
container = []
flex = []
grid = []
grid-responsive = []
section = []
switch = []
switch-size = []
switch-variant = []
switch-color = []
switch-high-contrast = []
switch-radius = []
switch-alignment = []
switch-disabled = []
