[package]
name = "radix-yew-themes"
description = "Yew port of Radix Themes."
homepage = "https://radix.rustforweb.org/themes/index.html"

authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
radix-yew-direction = { path = "../../primitives/yew/direction", version = "0.0.2" }
radix-yew-select = { path = "../../primitives/yew/select", version = "0.0.2" }
radix-yew-switch = { path = "../../primitives/yew/switch", version = "0.0.2" }
radix-yew-visually-hidden = { path = "../../primitives/yew/visually-hidden", version = "0.0.2" }
yew.workspace = true
