[package]
name = "radix-yew-select"
description = "Yew port of Radix Select."
homepage = "https://radix.rustforweb.org/primitives/components/select.html"

authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
radix-yew-compose-refs = { path = "../compose-refs", version = "0.0.2" }
radix-yew-direction = { path = "../direction", version = "0.0.2" }
radix-yew-popper = { path = "../popper", version = "0.0.2" }
radix-yew-primitive = { path = "../primitive", version = "0.0.2" }
radix-yew-use-controllable-state = { path = "../use-controllable-state", version = "0.0.2" }
web-sys.workspace = true
yew.workspace = true
yew-attrs.workspace = true
