[package]
name = "radix-yew-select"
description = "Yew port of Radix Select."
homepage = "https://radix.rustforweb.org/primitives/components/select.html"

authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
log.workspace = true
radix-number = { path = "../../core/number", version = "0.0.2" }
radix-yew-collection = { path = "../collection", version = "0.0.2" }
radix-yew-direction = { path = "../direction", version = "0.0.2" }
radix-yew-focus-guards = { path = "../focus-guards", version = "0.0.2" }
radix-yew-focus-scope = { path = "../focus-scope", version = "0.0.2" }
radix-yew-id = { path = "../id", version = "0.0.2" }
radix-yew-popper = { path = "../popper", version = "0.0.2" }
radix-yew-portal = { path = "../portal", version = "0.0.2" }
radix-yew-primitive = { path = "../primitive", version = "0.0.2" }
radix-yew-use-controllable-state = { path = "../use-controllable-state", version = "0.0.2" }
radix-yew-visually-hidden = { path = "../visually-hidden", version = "0.0.2" }
web-sys = { workspace = true, features = [
    "FocusOptions",
    "HtmlSelectElement",
    "ScrollIntoViewOptions",
    "ScrollLogicalPosition",
] }
yew.workspace = true
yew-struct-component.workspace = true
