[package]
name = "radix-yew-visually-hidden"
description = "Yew port of Radix Visually Hidden."
homepage = "https://radix.rustforweb.org/primitives/utilities/visually-hidden.html"

authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
radix-yew-primitive = { path = "../primitive", version = "0.0.2" }
yew.workspace = true
yew-attrs.workspace = true
